---

- hosts: all
  become: yes
  tasks:

    - name: update repository index
      apt:
        update_cache: yes

    - name: apache2 install
      apt:
        name: apache2
        state: latest

    - name: add php support for apache
      apt:
        name: libapache2-mod-php
        state: latest 
