- name: "Register HOME"
  shell: echo $HOME
  register: user_home
  become: yes
  become_user: "{{ item }}"
  changed_when: False
  become_method: enable

- name: "Load ps-twtty"
  lineinfile:
    path: '{{ user_home.stdout }}/.bashrc'
    line: "[ -f {{ ps_twtty_path }}/ps-twtty-7.sh ] && source {{ ps_twtty_path }}/ps-twtty-7.sh"
