- name: add ssh key for simone
  tags: always
  authorized_key:
    user: simone
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIChYNsZGjsbB2fwl+omS3OstvSp09N9jOAfeoka79I8K ansible"

- name: generate ssh_config file from telmplate
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restarted_sshd
